language: java
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lftp
script:
  - mvn clean deploy --settings .maven.settings
after_script:
  - lftp "$UPLOADER_USER:$UPLOADER_PASSWORD:$UPLOADER_HOST" -e "mkdir -f uploads/box2dlights; mput target/*.jar -O uploads/box2dlights; bye"